### ISSUE TITLE
BioModel Discussion Issue for eos7d58

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos7d58#6]
**Summary !!!**

- **BioModel Name**: Swanson2023 - ADMET-AI: To evaluate the pharmacokinetics property of large-scale chemical libraries

- **BioModel Tag**: Machine learning model, Ersilia

- **Metadata Comments**: 
Hi @GemmaTuron , for this model, each of the 6 predictions has a sub-predicitions. I'd like to clarify if all the sub-predictions are incorporated in Ersilia. 

- **Contributor**:
> 
 | roles             | Names | 
 | :---------------- | :------: | 
 | Curator        |   @Zainab-ik   | 
 | Code contributor      |   @DhanshreeA       | 
 | Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated

- **Annotation file**: [here](https://docs.google.com/spreadsheets/d/1Tu5HCSCUbTqk8urTmxxB_46b_xUsAsx-fstrXHCy9n4/edit?usp=sharing)

**Comment by GemmaTuron** [comment]
The 6 "predictions" are simply classes so that the outputs are better classified - ADME (Absortion, Distribution... these are "classes")
The endpoints we need to identify are for example: solubility, CYP3A4 inhibition and so on

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron 
I've annotated all the endpoints for this model. And the DOME annotation for output is just - _Model-Output_ since it's either classification or regression.

**Comment by GemmaTuron** [comment]
Thanks for the work @Zainab-ik this looks good, all endpoints are there
